modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/hnOsmium0001/GLFWWindow-Demo/issues"
[[mods]]
modId="glfwdemo"
version="${file.jarVersion}"
displayName="HarmonicsCore Demo"
displayURL="https://github.com/hnOsmium0001/GLFWWindow-Demo"
authors="hnOsmium0001"
description='''
'''

[[dependencies.glfwdemo]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.glfwdemo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
