modLoader="kotlinfml"
loaderVersion="[1,)"

[[mods]]
    modId="glfwdemo"
    version="${file.jarVersion}"
    displayName="GLFW Demo"
    displayURL="https://github.com/hnOsmium0001/GLFWWindow-Demo"
    issueTrackerURL="https://github.com/hnOsmium0001/GLFWWindow-Demo/issues"
    authors="hnOsmium0001"
    description='''
    '''

[[dependencies.glfwdemo]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.glfwdemo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
